### ISSUE TITLE
Error compiling SCSS inline comments

### ISSUE THREAD

**Issue by winghouchan** [jaumefontal/SASS-Build-SublimeText2#21]
There is an error compiling SCSS inline comments.

Say I have this code:

``` scss
html {
  font-family: sans-serif; // 1
  -ms-text-size-adjust: 100%; // 2
  -webkit-text-size-adjust: 100%; //2
}
```

Upon compilation an error will be generated:
![error_pic](https://cloud.githubusercontent.com/assets/6061021/2905059/6f8d2d28-d601-11e3-89b2-e0f1cca6d429.jpg)
